<?php
/**
 * AudioAsset
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shotstack
 *
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ShotstackClient\Model;

use \ArrayAccess;
use \ShotstackClient\ObjectSerializer;

/**
 * AudioAsset Class Doc Comment
 *
 * @category Class
 * @description The AudioAsset adds audio to a Clip. The audio can be sourced from a URL (&#x60;src&#x60;) or generated from a text prompt (&#x60;prompt&#x60;). Exactly one of &#x60;src&#x60; or &#x60;prompt&#x60; must be provided.  - **Source URL:** set &#x60;src&#x60; to a publicly accessible audio URL (e.g. mp3). - **Generated speech:** set &#x60;prompt&#x60; to the spoken text and &#x60;voice&#x60; to a voice   identifier (text-to-speech). Optionally set &#x60;language&#x60;/&#x60;newscaster&#x60;. - **Generated music or SFX:** set &#x60;prompt&#x60; describing the sound; omit &#x60;voice&#x60;. - Use &#x60;model&#x60; to choose the generator. The generated &#x60;src&#x60; is filled in   automatically.
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AudioAsset implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AudioAsset';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'src' => 'string',
        'prompt' => 'string',
        'voice' => 'string',
        'language' => 'string',
        'newscaster' => 'bool',
        'model' => 'string',
        'trim' => 'float',
        'volume' => '\ShotstackClient\Model\AudioAssetVolume',
        'speed' => 'float',
        'effect' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'src' => null,
        'prompt' => null,
        'voice' => null,
        'language' => null,
        'newscaster' => null,
        'model' => null,
        'trim' => null,
        'volume' => null,
        'speed' => 'float',
        'effect' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'src' => false,
        'prompt' => false,
        'voice' => false,
        'language' => false,
        'newscaster' => false,
        'model' => false,
        'trim' => false,
        'volume' => false,
        'speed' => false,
        'effect' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'src' => 'src',
        'prompt' => 'prompt',
        'voice' => 'voice',
        'language' => 'language',
        'newscaster' => 'newscaster',
        'model' => 'model',
        'trim' => 'trim',
        'volume' => 'volume',
        'speed' => 'speed',
        'effect' => 'effect'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'src' => 'setSrc',
        'prompt' => 'setPrompt',
        'voice' => 'setVoice',
        'language' => 'setLanguage',
        'newscaster' => 'setNewscaster',
        'model' => 'setModel',
        'trim' => 'setTrim',
        'volume' => 'setVolume',
        'speed' => 'setSpeed',
        'effect' => 'setEffect'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'src' => 'getSrc',
        'prompt' => 'getPrompt',
        'voice' => 'getVoice',
        'language' => 'getLanguage',
        'newscaster' => 'getNewscaster',
        'model' => 'getModel',
        'trim' => 'getTrim',
        'volume' => 'getVolume',
        'speed' => 'getSpeed',
        'effect' => 'getEffect'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_AUDIO = 'audio';
    public const EFFECT_NONE = 'none';
    public const EFFECT_FADE_IN = 'fadeIn';
    public const EFFECT_FADE_OUT = 'fadeOut';
    public const EFFECT_FADE_IN_FADE_OUT = 'fadeInFadeOut';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_AUDIO,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEffectAllowableValues()
    {
        return [
            self::EFFECT_NONE,
            self::EFFECT_FADE_IN,
            self::EFFECT_FADE_OUT,
            self::EFFECT_FADE_IN_FADE_OUT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('type', $data ?? [], 'audio');
        $this->setIfExists('src', $data ?? [], null);
        $this->setIfExists('prompt', $data ?? [], null);
        $this->setIfExists('voice', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('newscaster', $data ?? [], false);
        $this->setIfExists('model', $data ?? [], null);
        $this->setIfExists('trim', $data ?? [], null);
        $this->setIfExists('volume', $data ?? [], null);
        $this->setIfExists('speed', $data ?? [], null);
        $this->setIfExists('effect', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['src']) && (mb_strlen($this->container['src']) < 1)) {
            $invalidProperties[] = "invalid value for 'src', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['src']) && !preg_match("/\\S/", $this->container['src'])) {
            $invalidProperties[] = "invalid value for 'src', must be conform to the pattern /\\S/.";
        }

        if (!is_null($this->container['prompt']) && (mb_strlen($this->container['prompt']) > 4000)) {
            $invalidProperties[] = "invalid value for 'prompt', the character length must be smaller than or equal to 4000.";
        }

        if (!is_null($this->container['speed']) && ($this->container['speed'] > 10)) {
            $invalidProperties[] = "invalid value for 'speed', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['speed']) && ($this->container['speed'] < 0)) {
            $invalidProperties[] = "invalid value for 'speed', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getEffectAllowableValues();
        if (!is_null($this->container['effect']) && !in_array($this->container['effect'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'effect', must be one of '%s'",
                $this->container['effect'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The type of asset - set to `audio` for audio assets.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets src
     *
     * @return string|null
     */
    public function getSrc()
    {
        return $this->container['src'];
    }

    /**
     * Sets src
     *
     * @param string|null $src The audio source URL. The URL must be publicly accessible or include credentials. Provide either `src` or `prompt`, not both.
     *
     * @return self
     */
    public function setSrc($src)
    {
        if (is_null($src)) {
            throw new \InvalidArgumentException('non-nullable src cannot be null');
        }

        if ((mb_strlen($src) < 1)) {
            throw new \InvalidArgumentException('invalid length for $src when calling AudioAsset., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/\\S/", ObjectSerializer::toString($src)))) {
            throw new \InvalidArgumentException("invalid value for \$src when calling AudioAsset., must conform to the pattern /\\S/.");
        }

        $this->container['src'] = $src;

        return $this;
    }

    /**
     * Gets prompt
     *
     * @return string|null
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string|null $prompt A text prompt. When `voice` is set, the prompt is the spoken text (text-to-speech). Without `voice`, the prompt describes generated music or sound effects. The generated `src` is filled in automatically.
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }
        if ((mb_strlen($prompt) > 4000)) {
            throw new \InvalidArgumentException('invalid length for $prompt when calling AudioAsset., must be smaller than or equal to 4000.');
        }

        $this->container['prompt'] = $prompt;

        return $this;
    }

    /**
     * Gets voice
     *
     * @return string|null
     */
    public function getVoice()
    {
        return $this->container['voice'];
    }

    /**
     * Sets voice
     *
     * @param string|null $voice Voice identifier for text-to-speech generation (e.g. `Matthew`, `Joanna`). Only meaningful when `prompt` is set.
     *
     * @return self
     */
    public function setVoice($voice)
    {
        if (is_null($voice)) {
            throw new \InvalidArgumentException('non-nullable voice cannot be null');
        }
        $this->container['voice'] = $voice;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language Optional BCP-47 language code (e.g. `en-US`) for text-to-speech. Only meaningful when `prompt` and `voice` are set.
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets newscaster
     *
     * @return bool|null
     */
    public function getNewscaster()
    {
        return $this->container['newscaster'];
    }

    /**
     * Sets newscaster
     *
     * @param bool|null $newscaster Set to `true` to use the voice's newscaster mode when supported. Only meaningful when `prompt` and `voice` are set.
     *
     * @return self
     */
    public function setNewscaster($newscaster)
    {
        if (is_null($newscaster)) {
            throw new \InvalidArgumentException('non-nullable newscaster cannot be null');
        }
        $this->container['newscaster'] = $newscaster;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string|null $model The generation model to use when `prompt` is set (e.g. `polly-neural`). Defaults to the platform's preferred generator if omitted.
     *
     * @return self
     */
    public function setModel($model)
    {
        if (is_null($model)) {
            throw new \InvalidArgumentException('non-nullable model cannot be null');
        }
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets trim
     *
     * @return float|null
     */
    public function getTrim()
    {
        return $this->container['trim'];
    }

    /**
     * Sets trim
     *
     * @param float|null $trim The start trim point of the audio clip, in seconds (defaults to 0). Audio will start from the in trim point. The audio will play until the file ends or the Clip length is reached.
     *
     * @return self
     */
    public function setTrim($trim)
    {
        if (is_null($trim)) {
            throw new \InvalidArgumentException('non-nullable trim cannot be null');
        }
        $this->container['trim'] = $trim;

        return $this;
    }

    /**
     * Gets volume
     *
     * @return \ShotstackClient\Model\AudioAssetVolume|null
     */
    public function getVolume()
    {
        return $this->container['volume'];
    }

    /**
     * Sets volume
     *
     * @param \ShotstackClient\Model\AudioAssetVolume|null $volume volume
     *
     * @return self
     */
    public function setVolume($volume)
    {
        if (is_null($volume)) {
            throw new \InvalidArgumentException('non-nullable volume cannot be null');
        }
        $this->container['volume'] = $volume;

        return $this;
    }

    /**
     * Gets speed
     *
     * @return float|null
     */
    public function getSpeed()
    {
        return $this->container['speed'];
    }

    /**
     * Sets speed
     *
     * @param float|null $speed Adjust the playback speed of the audio clip between 0 (paused) and 10 (10x normal speed), where 1 is normal speed (defaults to 1). Adjusting the speed will also adjust the duration of the clip and may require you to adjust the Clip length. For example, if you set speed to 0.5, the clip will need to be 2x as long to play the entire audio (i.e. original length / 0.5). If you set speed to 2, the clip will need to be half as long to play the entire audio (i.e. original length / 2).
     *
     * @return self
     */
    public function setSpeed($speed)
    {
        if (is_null($speed)) {
            throw new \InvalidArgumentException('non-nullable speed cannot be null');
        }

        if (($speed > 10)) {
            throw new \InvalidArgumentException('invalid value for $speed when calling AudioAsset., must be smaller than or equal to 10.');
        }
        if (($speed < 0)) {
            throw new \InvalidArgumentException('invalid value for $speed when calling AudioAsset., must be bigger than or equal to 0.');
        }

        $this->container['speed'] = $speed;

        return $this;
    }

    /**
     * Gets effect
     *
     * @return string|null
     */
    public function getEffect()
    {
        return $this->container['effect'];
    }

    /**
     * Sets effect
     *
     * @param string|null $effect The effect to apply to the audio asset <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>
     *
     * @return self
     */
    public function setEffect($effect)
    {
        if (is_null($effect)) {
            throw new \InvalidArgumentException('non-nullable effect cannot be null');
        }
        $allowedValues = $this->getEffectAllowableValues();
        if (!in_array($effect, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'effect', must be one of '%s'",
                    $effect,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['effect'] = $effect;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


