<?php
/**
 * Clip
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shotstack
 *
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ShotstackClient\Model;

use \ArrayAccess;
use \ShotstackClient\ObjectSerializer;

/**
 * Clip Class Doc Comment
 *
 * @category Class
 * @description A clip is a container for a specific type of asset, i.e. a title, image, video, audio or html. You use a Clip to define when an asset will display on the timeline, how long it will play for and transitions, filters and effects to apply to it.
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Clip implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Clip';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'asset' => '\ShotstackClient\Model\Asset',
        'start' => '\ShotstackClient\Model\ClipStart',
        'length' => '\ShotstackClient\Model\ClipLength',
        'fit' => 'string',
        'scale' => '\ShotstackClient\Model\ClipScale',
        'width' => 'float',
        'height' => 'float',
        'position' => 'string',
        'offset' => '\ShotstackClient\Model\Offset',
        'transition' => '\ShotstackClient\Model\Transition',
        'effect' => 'string',
        'filter' => 'string',
        'opacity' => '\ShotstackClient\Model\ClipOpacity',
        'transform' => '\ShotstackClient\Model\Transformation',
        'alias' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'asset' => null,
        'start' => null,
        'length' => null,
        'fit' => null,
        'scale' => null,
        'width' => 'float',
        'height' => 'float',
        'position' => null,
        'offset' => null,
        'transition' => null,
        'effect' => null,
        'filter' => null,
        'opacity' => null,
        'transform' => null,
        'alias' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'asset' => false,
        'start' => false,
        'length' => false,
        'fit' => false,
        'scale' => false,
        'width' => false,
        'height' => false,
        'position' => false,
        'offset' => false,
        'transition' => false,
        'effect' => false,
        'filter' => false,
        'opacity' => false,
        'transform' => false,
        'alias' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'asset' => 'asset',
        'start' => 'start',
        'length' => 'length',
        'fit' => 'fit',
        'scale' => 'scale',
        'width' => 'width',
        'height' => 'height',
        'position' => 'position',
        'offset' => 'offset',
        'transition' => 'transition',
        'effect' => 'effect',
        'filter' => 'filter',
        'opacity' => 'opacity',
        'transform' => 'transform',
        'alias' => 'alias'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'asset' => 'setAsset',
        'start' => 'setStart',
        'length' => 'setLength',
        'fit' => 'setFit',
        'scale' => 'setScale',
        'width' => 'setWidth',
        'height' => 'setHeight',
        'position' => 'setPosition',
        'offset' => 'setOffset',
        'transition' => 'setTransition',
        'effect' => 'setEffect',
        'filter' => 'setFilter',
        'opacity' => 'setOpacity',
        'transform' => 'setTransform',
        'alias' => 'setAlias'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'asset' => 'getAsset',
        'start' => 'getStart',
        'length' => 'getLength',
        'fit' => 'getFit',
        'scale' => 'getScale',
        'width' => 'getWidth',
        'height' => 'getHeight',
        'position' => 'getPosition',
        'offset' => 'getOffset',
        'transition' => 'getTransition',
        'effect' => 'getEffect',
        'filter' => 'getFilter',
        'opacity' => 'getOpacity',
        'transform' => 'getTransform',
        'alias' => 'getAlias'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FIT_COVER = 'cover';
    public const FIT_CONTAIN = 'contain';
    public const FIT_CROP = 'crop';
    public const FIT_NONE = 'none';
    public const POSITION_TOP = 'top';
    public const POSITION_TOP_RIGHT = 'topRight';
    public const POSITION_RIGHT = 'right';
    public const POSITION_BOTTOM_RIGHT = 'bottomRight';
    public const POSITION_BOTTOM = 'bottom';
    public const POSITION_BOTTOM_LEFT = 'bottomLeft';
    public const POSITION_LEFT = 'left';
    public const POSITION_TOP_LEFT = 'topLeft';
    public const POSITION_CENTER = 'center';
    public const EFFECT_ZOOM_IN = 'zoomIn';
    public const EFFECT_ZOOM_IN_SLOW = 'zoomInSlow';
    public const EFFECT_ZOOM_IN_FAST = 'zoomInFast';
    public const EFFECT_ZOOM_OUT = 'zoomOut';
    public const EFFECT_ZOOM_OUT_SLOW = 'zoomOutSlow';
    public const EFFECT_ZOOM_OUT_FAST = 'zoomOutFast';
    public const EFFECT_SLIDE_LEFT = 'slideLeft';
    public const EFFECT_SLIDE_LEFT_SLOW = 'slideLeftSlow';
    public const EFFECT_SLIDE_LEFT_FAST = 'slideLeftFast';
    public const EFFECT_SLIDE_RIGHT = 'slideRight';
    public const EFFECT_SLIDE_RIGHT_SLOW = 'slideRightSlow';
    public const EFFECT_SLIDE_RIGHT_FAST = 'slideRightFast';
    public const EFFECT_SLIDE_UP = 'slideUp';
    public const EFFECT_SLIDE_UP_SLOW = 'slideUpSlow';
    public const EFFECT_SLIDE_UP_FAST = 'slideUpFast';
    public const EFFECT_SLIDE_DOWN = 'slideDown';
    public const EFFECT_SLIDE_DOWN_SLOW = 'slideDownSlow';
    public const EFFECT_SLIDE_DOWN_FAST = 'slideDownFast';
    public const FILTER_NONE = 'none';
    public const FILTER_BLUR = 'blur';
    public const FILTER_BOOST = 'boost';
    public const FILTER_CONTRAST = 'contrast';
    public const FILTER_DARKEN = 'darken';
    public const FILTER_GREYSCALE = 'greyscale';
    public const FILTER_LIGHTEN = 'lighten';
    public const FILTER_MUTED = 'muted';
    public const FILTER_NEGATIVE = 'negative';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFitAllowableValues()
    {
        return [
            self::FIT_COVER,
            self::FIT_CONTAIN,
            self::FIT_CROP,
            self::FIT_NONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPositionAllowableValues()
    {
        return [
            self::POSITION_TOP,
            self::POSITION_TOP_RIGHT,
            self::POSITION_RIGHT,
            self::POSITION_BOTTOM_RIGHT,
            self::POSITION_BOTTOM,
            self::POSITION_BOTTOM_LEFT,
            self::POSITION_LEFT,
            self::POSITION_TOP_LEFT,
            self::POSITION_CENTER,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEffectAllowableValues()
    {
        return [
            self::EFFECT_ZOOM_IN,
            self::EFFECT_ZOOM_IN_SLOW,
            self::EFFECT_ZOOM_IN_FAST,
            self::EFFECT_ZOOM_OUT,
            self::EFFECT_ZOOM_OUT_SLOW,
            self::EFFECT_ZOOM_OUT_FAST,
            self::EFFECT_SLIDE_LEFT,
            self::EFFECT_SLIDE_LEFT_SLOW,
            self::EFFECT_SLIDE_LEFT_FAST,
            self::EFFECT_SLIDE_RIGHT,
            self::EFFECT_SLIDE_RIGHT_SLOW,
            self::EFFECT_SLIDE_RIGHT_FAST,
            self::EFFECT_SLIDE_UP,
            self::EFFECT_SLIDE_UP_SLOW,
            self::EFFECT_SLIDE_UP_FAST,
            self::EFFECT_SLIDE_DOWN,
            self::EFFECT_SLIDE_DOWN_SLOW,
            self::EFFECT_SLIDE_DOWN_FAST,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFilterAllowableValues()
    {
        return [
            self::FILTER_NONE,
            self::FILTER_BLUR,
            self::FILTER_BOOST,
            self::FILTER_CONTRAST,
            self::FILTER_DARKEN,
            self::FILTER_GREYSCALE,
            self::FILTER_LIGHTEN,
            self::FILTER_MUTED,
            self::FILTER_NEGATIVE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('asset', $data ?? [], null);
        $this->setIfExists('start', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('fit', $data ?? [], null);
        $this->setIfExists('scale', $data ?? [], null);
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('offset', $data ?? [], null);
        $this->setIfExists('transition', $data ?? [], null);
        $this->setIfExists('effect', $data ?? [], null);
        $this->setIfExists('filter', $data ?? [], null);
        $this->setIfExists('opacity', $data ?? [], null);
        $this->setIfExists('transform', $data ?? [], null);
        $this->setIfExists('alias', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['asset'] === null) {
            $invalidProperties[] = "'asset' can't be null";
        }
        if ($this->container['start'] === null) {
            $invalidProperties[] = "'start' can't be null";
        }
        if ($this->container['length'] === null) {
            $invalidProperties[] = "'length' can't be null";
        }
        $allowedValues = $this->getFitAllowableValues();
        if (!is_null($this->container['fit']) && !in_array($this->container['fit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fit', must be one of '%s'",
                $this->container['fit'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['width']) && ($this->container['width'] > 3840)) {
            $invalidProperties[] = "invalid value for 'width', must be smaller than or equal to 3840.";
        }

        if (!is_null($this->container['width']) && ($this->container['width'] < 1)) {
            $invalidProperties[] = "invalid value for 'width', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['height']) && ($this->container['height'] > 2160)) {
            $invalidProperties[] = "invalid value for 'height', must be smaller than or equal to 2160.";
        }

        if (!is_null($this->container['height']) && ($this->container['height'] < 1)) {
            $invalidProperties[] = "invalid value for 'height', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getPositionAllowableValues();
        if (!is_null($this->container['position']) && !in_array($this->container['position'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'position', must be one of '%s'",
                $this->container['position'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getEffectAllowableValues();
        if (!is_null($this->container['effect']) && !in_array($this->container['effect'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'effect', must be one of '%s'",
                $this->container['effect'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFilterAllowableValues();
        if (!is_null($this->container['filter']) && !in_array($this->container['filter'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'filter', must be one of '%s'",
                $this->container['filter'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['alias']) && !preg_match("/^[A-Za-z0-9_-]+$/", $this->container['alias'])) {
            $invalidProperties[] = "invalid value for 'alias', must be conform to the pattern /^[A-Za-z0-9_-]+$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets asset
     *
     * @return \ShotstackClient\Model\Asset
     */
    public function getAsset()
    {
        return $this->container['asset'];
    }

    /**
     * Sets asset
     *
     * @param \ShotstackClient\Model\Asset $asset asset
     *
     * @return self
     */
    public function setAsset($asset)
    {
        if (is_null($asset)) {
            throw new \InvalidArgumentException('non-nullable asset cannot be null');
        }
        $this->container['asset'] = $asset;

        return $this;
    }

    /**
     * Gets start
     *
     * @return \ShotstackClient\Model\ClipStart
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param \ShotstackClient\Model\ClipStart $start start
     *
     * @return self
     */
    public function setStart($start)
    {
        if (is_null($start)) {
            throw new \InvalidArgumentException('non-nullable start cannot be null');
        }
        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets length
     *
     * @return \ShotstackClient\Model\ClipLength
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param \ShotstackClient\Model\ClipLength $length length
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets fit
     *
     * @return string|null
     */
    public function getFit()
    {
        return $this->container['fit'];
    }

    /**
     * Sets fit
     *
     * @param string|null $fit Set how the asset should be scaled to fit the viewport using one of the following options:    <ul>     <li>`crop` <b>(default)</b> - scale the asset to fill the viewport while maintaining the aspect ratio. The asset will be cropped if it exceeds the bounds of the viewport.</li>     <li>`cover` - stretch the asset to fill the viewport without maintaining the aspect ratio.</li>     <li>`contain` - fit the entire asset within the viewport while maintaining the original aspect ratio.</li>     <li>`none` - preserves the original asset dimensions and does not apply any scaling.</li>   </ul>
     *
     * @return self
     */
    public function setFit($fit)
    {
        if (is_null($fit)) {
            throw new \InvalidArgumentException('non-nullable fit cannot be null');
        }
        $allowedValues = $this->getFitAllowableValues();
        if (!in_array($fit, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fit', must be one of '%s'",
                    $fit,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fit'] = $fit;

        return $this;
    }

    /**
     * Gets scale
     *
     * @return \ShotstackClient\Model\ClipScale|null
     */
    public function getScale()
    {
        return $this->container['scale'];
    }

    /**
     * Sets scale
     *
     * @param \ShotstackClient\Model\ClipScale|null $scale scale
     *
     * @return self
     */
    public function setScale($scale)
    {
        if (is_null($scale)) {
            throw new \InvalidArgumentException('non-nullable scale cannot be null');
        }
        $this->container['scale'] = $scale;

        return $this;
    }

    /**
     * Gets width
     *
     * @return float|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param float|null $width Set the width of the clip bounding box in pixels. This constrains the width of the clip, overriding the default behavior where clips fill the viewport width.
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            throw new \InvalidArgumentException('non-nullable width cannot be null');
        }

        if (($width > 3840)) {
            throw new \InvalidArgumentException('invalid value for $width when calling Clip., must be smaller than or equal to 3840.');
        }
        if (($width < 1)) {
            throw new \InvalidArgumentException('invalid value for $width when calling Clip., must be bigger than or equal to 1.');
        }

        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return float|null
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param float|null $height Set the height of the clip bounding box in pixels. This constrains the height of the clip, overriding the default behavior where clips fill the viewport height.
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            throw new \InvalidArgumentException('non-nullable height cannot be null');
        }

        if (($height > 2160)) {
            throw new \InvalidArgumentException('invalid value for $height when calling Clip., must be smaller than or equal to 2160.');
        }
        if (($height < 1)) {
            throw new \InvalidArgumentException('invalid value for $height when calling Clip., must be bigger than or equal to 1.');
        }

        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets position
     *
     * @return string|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param string|null $position Place the asset in one of nine predefined positions of the viewport. This is most effective for when the asset is scaled and you want to position the element to a specific position. <ul>   <li>`top` - top (center)</li>   <li>`topRight` - top right</li>   <li>`right` - right (center)</li>   <li>`bottomRight` - bottom right</li>   <li>`bottom` - bottom (center)</li>   <li>`bottomLeft` - bottom left</li>   <li>`left` - left (center)</li>   <li>`topLeft` - top left</li>   <li>`center` - center</li> </ul>
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            throw new \InvalidArgumentException('non-nullable position cannot be null');
        }
        $allowedValues = $this->getPositionAllowableValues();
        if (!in_array($position, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'position', must be one of '%s'",
                    $position,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets offset
     *
     * @return \ShotstackClient\Model\Offset|null
     */
    public function getOffset()
    {
        return $this->container['offset'];
    }

    /**
     * Sets offset
     *
     * @param \ShotstackClient\Model\Offset|null $offset offset
     *
     * @return self
     */
    public function setOffset($offset)
    {
        if (is_null($offset)) {
            throw new \InvalidArgumentException('non-nullable offset cannot be null');
        }
        $this->container['offset'] = $offset;

        return $this;
    }

    /**
     * Gets transition
     *
     * @return \ShotstackClient\Model\Transition|null
     */
    public function getTransition()
    {
        return $this->container['transition'];
    }

    /**
     * Sets transition
     *
     * @param \ShotstackClient\Model\Transition|null $transition transition
     *
     * @return self
     */
    public function setTransition($transition)
    {
        if (is_null($transition)) {
            throw new \InvalidArgumentException('non-nullable transition cannot be null');
        }
        $this->container['transition'] = $transition;

        return $this;
    }

    /**
     * Gets effect
     *
     * @return string|null
     */
    public function getEffect()
    {
        return $this->container['effect'];
    }

    /**
     * Sets effect
     *
     * @param string|null $effect A motion effect to apply to the Clip. <ul>   <li>`zoomIn` - slow zoom in</li>   <li>`zoomOut` - slow zoom out</li>   <li>`slideLeft` - slow slide (pan) left</li>   <li>`slideRight` - slow slide (pan) right</li>   <li>`slideUp` - slow slide (pan) up</li>   <li>`slideDown` - slow slide (pan) down</li> </ul> The motion effect speed can also be controlled by appending `Fast` or `Slow` to the effect, e.g. `zoomInFast` or `slideRightSlow`.
     *
     * @return self
     */
    public function setEffect($effect)
    {
        if (is_null($effect)) {
            throw new \InvalidArgumentException('non-nullable effect cannot be null');
        }
        $allowedValues = $this->getEffectAllowableValues();
        if (!in_array($effect, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'effect', must be one of '%s'",
                    $effect,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['effect'] = $effect;

        return $this;
    }

    /**
     * Gets filter
     *
     * @return string|null
     */
    public function getFilter()
    {
        return $this->container['filter'];
    }

    /**
     * Sets filter
     *
     * @param string|null $filter A filter effect to apply to the Clip. <ul>   <li>`none` - no filter applied</li>   <li>`blur` - blur the scene</li>   <li>`boost` - boost contrast and saturation</li>   <li>`contrast` - increase contrast</li>   <li>`darken` - darken the scene</li>   <li>`greyscale` - remove colour</li>   <li>`lighten` - lighten the scene</li>   <li>`muted` - reduce saturation and contrast</li>   <li>`negative` - negative colors</li> </ul>
     *
     * @return self
     */
    public function setFilter($filter)
    {
        if (is_null($filter)) {
            throw new \InvalidArgumentException('non-nullable filter cannot be null');
        }
        $allowedValues = $this->getFilterAllowableValues();
        if (!in_array($filter, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'filter', must be one of '%s'",
                    $filter,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['filter'] = $filter;

        return $this;
    }

    /**
     * Gets opacity
     *
     * @return \ShotstackClient\Model\ClipOpacity|null
     */
    public function getOpacity()
    {
        return $this->container['opacity'];
    }

    /**
     * Sets opacity
     *
     * @param \ShotstackClient\Model\ClipOpacity|null $opacity opacity
     *
     * @return self
     */
    public function setOpacity($opacity)
    {
        if (is_null($opacity)) {
            throw new \InvalidArgumentException('non-nullable opacity cannot be null');
        }
        $this->container['opacity'] = $opacity;

        return $this;
    }

    /**
     * Gets transform
     *
     * @return \ShotstackClient\Model\Transformation|null
     */
    public function getTransform()
    {
        return $this->container['transform'];
    }

    /**
     * Sets transform
     *
     * @param \ShotstackClient\Model\Transformation|null $transform transform
     *
     * @return self
     */
    public function setTransform($transform)
    {
        if (is_null($transform)) {
            throw new \InvalidArgumentException('non-nullable transform cannot be null');
        }
        $this->container['transform'] = $transform;

        return $this;
    }

    /**
     * Gets alias
     *
     * @return string|null
     */
    public function getAlias()
    {
        return $this->container['alias'];
    }

    /**
     * Sets alias
     *
     * @param string|null $alias A unique identifier for this clip that can be used to reference it from other clips using the `alias://` protocol in asset sources. This is useful for features like auto-captioning where a caption asset needs to reference the audio from another clip.
     *
     * @return self
     */
    public function setAlias($alias)
    {
        if (is_null($alias)) {
            throw new \InvalidArgumentException('non-nullable alias cannot be null');
        }

        if ((!preg_match("/^[A-Za-z0-9_-]+$/", ObjectSerializer::toString($alias)))) {
            throw new \InvalidArgumentException("invalid value for \$alias when calling Clip., must conform to the pattern /^[A-Za-z0-9_-]+$/.");
        }

        $this->container['alias'] = $alias;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


