<?php
/**
 * Rendition
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shotstack
 *
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ShotstackClient\Model;

use \ArrayAccess;
use \ShotstackClient\ObjectSerializer;

/**
 * Rendition Class Doc Comment
 *
 * @category Class
 * @description A rendition is a new output file that is generated from the source. The rendition can be encoded to a different format and have transformations applied to it such as resizing, cropping, etc...
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Rendition implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Rendition';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'format' => 'string',
        'size' => '\ShotstackClient\Model\Size',
        'fit' => 'string',
        'resolution' => 'string',
        'quality' => 'int',
        'fps' => 'float',
        'speed' => '\ShotstackClient\Model\Speed',
        'keyframe_interval' => 'int',
        'fix_offset' => 'bool',
        'fix_rotation' => 'bool',
        'enhance' => '\ShotstackClient\Model\Enhancements',
        'filename' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'format' => null,
        'size' => null,
        'fit' => null,
        'resolution' => null,
        'quality' => null,
        'fps' => null,
        'speed' => null,
        'keyframe_interval' => null,
        'fix_offset' => null,
        'fix_rotation' => null,
        'enhance' => null,
        'filename' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'format' => false,
        'size' => false,
        'fit' => false,
        'resolution' => false,
        'quality' => false,
        'fps' => false,
        'speed' => false,
        'keyframe_interval' => false,
        'fix_offset' => false,
        'fix_rotation' => false,
        'enhance' => false,
        'filename' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'format' => 'format',
        'size' => 'size',
        'fit' => 'fit',
        'resolution' => 'resolution',
        'quality' => 'quality',
        'fps' => 'fps',
        'speed' => 'speed',
        'keyframe_interval' => 'keyframeInterval',
        'fix_offset' => 'fixOffset',
        'fix_rotation' => 'fixRotation',
        'enhance' => 'enhance',
        'filename' => 'filename'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'format' => 'setFormat',
        'size' => 'setSize',
        'fit' => 'setFit',
        'resolution' => 'setResolution',
        'quality' => 'setQuality',
        'fps' => 'setFps',
        'speed' => 'setSpeed',
        'keyframe_interval' => 'setKeyframeInterval',
        'fix_offset' => 'setFixOffset',
        'fix_rotation' => 'setFixRotation',
        'enhance' => 'setEnhance',
        'filename' => 'setFilename'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'format' => 'getFormat',
        'size' => 'getSize',
        'fit' => 'getFit',
        'resolution' => 'getResolution',
        'quality' => 'getQuality',
        'fps' => 'getFps',
        'speed' => 'getSpeed',
        'keyframe_interval' => 'getKeyframeInterval',
        'fix_offset' => 'getFixOffset',
        'fix_rotation' => 'getFixRotation',
        'enhance' => 'getEnhance',
        'filename' => 'getFilename'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FORMAT_MP4 = 'mp4';
    public const FORMAT_WEBM = 'webm';
    public const FORMAT_MOV = 'mov';
    public const FORMAT_AVI = 'avi';
    public const FORMAT_MKV = 'mkv';
    public const FORMAT_OGV = 'ogv';
    public const FORMAT_WMV = 'wmv';
    public const FORMAT_AVIF = 'avif';
    public const FORMAT_GIF = 'gif';
    public const FORMAT_MP3 = 'mp3';
    public const FORMAT_WAV = 'wav';
    public const FORMAT_JPG = 'jpg';
    public const FORMAT_PNG = 'png';
    public const FORMAT_WEBP = 'webp';
    public const FORMAT_TIF = 'tif';
    public const FIT_COVER = 'cover';
    public const FIT_CONTAIN = 'contain';
    public const FIT_CROP = 'crop';
    public const RESOLUTION_PREVIEW = 'preview';
    public const RESOLUTION_MOBILE = 'mobile';
    public const RESOLUTION_SD = 'sd';
    public const RESOLUTION_HD = 'hd';
    public const RESOLUTION_FHD = 'fhd';
    public const FPS_12 = 12;
    public const FPS_15 = 15;
    public const FPS_23_DOT_976 = 23.976;
    public const FPS_24 = 24;
    public const FPS_25 = 25;
    public const FPS_29_DOT_97 = 29.97;
    public const FPS_30 = 30;
    public const FPS_48 = 48;
    public const FPS_50 = 50;
    public const FPS_59_DOT_94 = 59.94;
    public const FPS_60 = 60;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFormatAllowableValues()
    {
        return [
            self::FORMAT_MP4,
            self::FORMAT_WEBM,
            self::FORMAT_MOV,
            self::FORMAT_AVI,
            self::FORMAT_MKV,
            self::FORMAT_OGV,
            self::FORMAT_WMV,
            self::FORMAT_AVIF,
            self::FORMAT_GIF,
            self::FORMAT_MP3,
            self::FORMAT_WAV,
            self::FORMAT_JPG,
            self::FORMAT_PNG,
            self::FORMAT_WEBP,
            self::FORMAT_TIF,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFitAllowableValues()
    {
        return [
            self::FIT_COVER,
            self::FIT_CONTAIN,
            self::FIT_CROP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getResolutionAllowableValues()
    {
        return [
            self::RESOLUTION_PREVIEW,
            self::RESOLUTION_MOBILE,
            self::RESOLUTION_SD,
            self::RESOLUTION_HD,
            self::RESOLUTION_FHD,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFpsAllowableValues()
    {
        return [
            self::FPS_12,
            self::FPS_15,
            self::FPS_23_DOT_976,
            self::FPS_24,
            self::FPS_25,
            self::FPS_29_DOT_97,
            self::FPS_30,
            self::FPS_48,
            self::FPS_50,
            self::FPS_59_DOT_94,
            self::FPS_60,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('format', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('fit', $data ?? [], null);
        $this->setIfExists('resolution', $data ?? [], null);
        $this->setIfExists('quality', $data ?? [], null);
        $this->setIfExists('fps', $data ?? [], null);
        $this->setIfExists('speed', $data ?? [], null);
        $this->setIfExists('keyframe_interval', $data ?? [], null);
        $this->setIfExists('fix_offset', $data ?? [], null);
        $this->setIfExists('fix_rotation', $data ?? [], null);
        $this->setIfExists('enhance', $data ?? [], null);
        $this->setIfExists('filename', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFormatAllowableValues();
        if (!is_null($this->container['format']) && !in_array($this->container['format'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'format', must be one of '%s'",
                $this->container['format'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFitAllowableValues();
        if (!is_null($this->container['fit']) && !in_array($this->container['fit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fit', must be one of '%s'",
                $this->container['fit'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getResolutionAllowableValues();
        if (!is_null($this->container['resolution']) && !in_array($this->container['resolution'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'resolution', must be one of '%s'",
                $this->container['resolution'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['quality']) && ($this->container['quality'] > 100)) {
            $invalidProperties[] = "invalid value for 'quality', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['quality']) && ($this->container['quality'] < 1)) {
            $invalidProperties[] = "invalid value for 'quality', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getFpsAllowableValues();
        if (!is_null($this->container['fps']) && !in_array($this->container['fps'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fps', must be one of '%s'",
                $this->container['fps'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['keyframe_interval']) && ($this->container['keyframe_interval'] > 300)) {
            $invalidProperties[] = "invalid value for 'keyframe_interval', must be smaller than or equal to 300.";
        }

        if (!is_null($this->container['keyframe_interval']) && ($this->container['keyframe_interval'] < 1)) {
            $invalidProperties[] = "invalid value for 'keyframe_interval', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets format
     *
     * @return string|null
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param string|null $format The output format to encode the file to. You can only encode a file to the same type, i.e. a video to a video or an image to an image. You can't encode a video as an image. The following formats are available: <ul>   <li>`mp4` - mp4 video file (video only)</li>   <li>`webm` - webm video file (video only)</li>   <li>`mov` - mov video file (video only)</li>   <li>`avi` - avi video file (video only)</li>   <li>`mkv` - mkv video file (video only)</li>   <li>`ogv` - ogv video file (video only)</li>   <li>`wmv` - wmv video file (video only)</li>   <li>`avif` - avif video file (video only)</li>   <li>`gif` - animated gif file (video only)</li>   <li>`jpg` - jpg image file (image only)</li>   <li>`png` - png image file (image only)</li>   <li>`webp` - webp image file (image only)</li>   <li>`tif` - tif image file (image only)</li>   <li>`mp3` - mp3 audio file (audio only)</li>   <li>`wav` - wav audio file (audio only)</li> </ul>
     *
     * @return self
     */
    public function setFormat($format)
    {
        if (is_null($format)) {
            throw new \InvalidArgumentException('non-nullable format cannot be null');
        }
        $allowedValues = $this->getFormatAllowableValues();
        if (!in_array($format, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'format', must be one of '%s'",
                    $format,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['format'] = $format;

        return $this;
    }

    /**
     * Gets size
     *
     * @return \ShotstackClient\Model\Size|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param \ShotstackClient\Model\Size|null $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets fit
     *
     * @return string|null
     */
    public function getFit()
    {
        return $this->container['fit'];
    }

    /**
     * Sets fit
     *
     * @param string|null $fit Set how the rendition should be scaled and cropped when using a size with an aspect ratio that is different from the source. Fit applies to both videos and images. <ul>   <li>`crop` <b>(default)</b> - scale the rendition to fill the output area while maintaining the aspect ratio. The rendition will be cropped if it exceeds the bounds of the output.</li>   <li>`cover` - stretch the rendition to fill the output without maintaining the aspect ratio.</li>   <li>`contain` - fit the entire rendition within the output while maintaining the original aspect ratio.</li> </ul>
     *
     * @return self
     */
    public function setFit($fit)
    {
        if (is_null($fit)) {
            throw new \InvalidArgumentException('non-nullable fit cannot be null');
        }
        $allowedValues = $this->getFitAllowableValues();
        if (!in_array($fit, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fit', must be one of '%s'",
                    $fit,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fit'] = $fit;

        return $this;
    }

    /**
     * Gets resolution
     *
     * @return string|null
     */
    public function getResolution()
    {
        return $this->container['resolution'];
    }

    /**
     * Sets resolution
     *
     * @param string|null $resolution The preset output resolution of the video or image. This is a convenience property that sets the width and height based on industry standard resolutions. The following resolutions are available: <ul>   <li>`preview` - 512px x 288px</li>   <li>`mobile` - 640px x 360px</li>   <li>`sd` - 1024px x 576px</li>   <li>`hd` - 1280px x 720px</li>   <li>`fhd` - 1920px x 1080px</li> </ul>
     *
     * @return self
     */
    public function setResolution($resolution)
    {
        if (is_null($resolution)) {
            throw new \InvalidArgumentException('non-nullable resolution cannot be null');
        }
        $allowedValues = $this->getResolutionAllowableValues();
        if (!in_array($resolution, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'resolution', must be one of '%s'",
                    $resolution,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['resolution'] = $resolution;

        return $this;
    }

    /**
     * Gets quality
     *
     * @return int|null
     */
    public function getQuality()
    {
        return $this->container['quality'];
    }

    /**
     * Sets quality
     *
     * @param int|null $quality Adjust the visual quality of the video or image. The higher the value, the sharper the image quality but the larger file size and slower the encoding process. When specifying quality, the goal is to balance file size vs visual quality. Quality is a value between 1 and 100 where 1 is fully compressed with low image quality and 100 is close to lossless with high image quality and large file size. Sane values are between 50 and 75. Omitting the quality parameter will result in an asset optimised for encoding speed, file size and visual quality.
     *
     * @return self
     */
    public function setQuality($quality)
    {
        if (is_null($quality)) {
            throw new \InvalidArgumentException('non-nullable quality cannot be null');
        }

        if (($quality > 100)) {
            throw new \InvalidArgumentException('invalid value for $quality when calling Rendition., must be smaller than or equal to 100.');
        }
        if (($quality < 1)) {
            throw new \InvalidArgumentException('invalid value for $quality when calling Rendition., must be bigger than or equal to 1.');
        }

        $this->container['quality'] = $quality;

        return $this;
    }

    /**
     * Gets fps
     *
     * @return float|null
     */
    public function getFps()
    {
        return $this->container['fps'];
    }

    /**
     * Sets fps
     *
     * @param float|null $fps Change the frame rate of a video asset. <ul>   <li>`12` - 12fps</li>   <li>`15` - 15fps</li>   <li>`24` - 24fps</li>   <li>`23.976` - 23.976fps</li>   <li>`25` (default) - 25fps</li>   <li>`29.97` - 29.97fps</li>   <li>`30` - 30fps</li>   <li>`48` - 48fps</li>   <li>`50` - 50fps</li>   <li>`59.94` - 59.94fps</li>   <li>`60` - 60fps</li> </ul>
     *
     * @return self
     */
    public function setFps($fps)
    {
        if (is_null($fps)) {
            throw new \InvalidArgumentException('non-nullable fps cannot be null');
        }
        $allowedValues = $this->getFpsAllowableValues();
        if (!in_array($fps, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fps', must be one of '%s'",
                    $fps,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fps'] = $fps;

        return $this;
    }

    /**
     * Gets speed
     *
     * @return \ShotstackClient\Model\Speed|null
     */
    public function getSpeed()
    {
        return $this->container['speed'];
    }

    /**
     * Sets speed
     *
     * @param \ShotstackClient\Model\Speed|null $speed speed
     *
     * @return self
     */
    public function setSpeed($speed)
    {
        if (is_null($speed)) {
            throw new \InvalidArgumentException('non-nullable speed cannot be null');
        }
        $this->container['speed'] = $speed;

        return $this;
    }

    /**
     * Gets keyframe_interval
     *
     * @return int|null
     */
    public function getKeyframeInterval()
    {
        return $this->container['keyframe_interval'];
    }

    /**
     * Sets keyframe_interval
     *
     * @param int|null $keyframe_interval The keyframe interval is useful to optimize playback, seeking and smoother scrubbing in browsers. The value sets the number of frames between a keyframe. The lower the number, the larger the file. Try a value between 10 and 25 for smooth scrubbing.
     *
     * @return self
     */
    public function setKeyframeInterval($keyframe_interval)
    {
        if (is_null($keyframe_interval)) {
            throw new \InvalidArgumentException('non-nullable keyframe_interval cannot be null');
        }

        if (($keyframe_interval > 300)) {
            throw new \InvalidArgumentException('invalid value for $keyframe_interval when calling Rendition., must be smaller than or equal to 300.');
        }
        if (($keyframe_interval < 1)) {
            throw new \InvalidArgumentException('invalid value for $keyframe_interval when calling Rendition., must be bigger than or equal to 1.');
        }

        $this->container['keyframe_interval'] = $keyframe_interval;

        return $this;
    }

    /**
     * Gets fix_offset
     *
     * @return bool|null
     */
    public function getFixOffset()
    {
        return $this->container['fix_offset'];
    }

    /**
     * Sets fix_offset
     *
     * @param bool|null $fix_offset Attempt to fix audio and video sync issues. This can occur when recording devices, such as smartphones and  web cams use compression techniques like [Variable Frame Rate](https://en.wikipedia.org/wiki/Variable_frame_rate)  (VFR) which can cause audio and video to go out of sync. This option will attempt to fix the sync issues.
     *
     * @return self
     */
    public function setFixOffset($fix_offset)
    {
        if (is_null($fix_offset)) {
            throw new \InvalidArgumentException('non-nullable fix_offset cannot be null');
        }
        $this->container['fix_offset'] = $fix_offset;

        return $this;
    }

    /**
     * Gets fix_rotation
     *
     * @return bool|null
     */
    public function getFixRotation()
    {
        return $this->container['fix_rotation'];
    }

    /**
     * Sets fix_rotation
     *
     * @param bool|null $fix_rotation Automatically reset the rotation of the video based on the orientation metadata in the video file. This is useful for videos recorded on smartphones that have orientation metadata that may not work correctly with certain video editing software, including the Shotstack Edit API.
     *
     * @return self
     */
    public function setFixRotation($fix_rotation)
    {
        if (is_null($fix_rotation)) {
            throw new \InvalidArgumentException('non-nullable fix_rotation cannot be null');
        }
        $this->container['fix_rotation'] = $fix_rotation;

        return $this;
    }

    /**
     * Gets enhance
     *
     * @return \ShotstackClient\Model\Enhancements|null
     */
    public function getEnhance()
    {
        return $this->container['enhance'];
    }

    /**
     * Sets enhance
     *
     * @param \ShotstackClient\Model\Enhancements|null $enhance enhance
     *
     * @return self
     */
    public function setEnhance($enhance)
    {
        if (is_null($enhance)) {
            throw new \InvalidArgumentException('non-nullable enhance cannot be null');
        }
        $this->container['enhance'] = $enhance;

        return $this;
    }

    /**
     * Gets filename
     *
     * @return string|null
     */
    public function getFilename()
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string|null $filename A custom name for the generated rendition file. The file extension will be automatically added based on the format of the rendition. If no filename is provided, the rendition ID will be used.
     *
     * @return self
     */
    public function setFilename($filename)
    {
        if (is_null($filename)) {
            throw new \InvalidArgumentException('non-nullable filename cannot be null');
        }
        $this->container['filename'] = $filename;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


