<?php
/**
 * RichCaptionActiveFont
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shotstack
 *
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ShotstackClient\Model;

use \ArrayAccess;
use \ShotstackClient\ObjectSerializer;

/**
 * RichCaptionActiveFont Class Doc Comment
 *
 * @category Class
 * @description Font properties for the active/highlighted word.
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RichCaptionActiveFont implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RichCaptionActiveFont';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'family' => 'string',
        'weight' => 'mixed',
        'color' => 'string',
        'background' => 'string',
        'opacity' => 'float',
        'size' => 'float',
        'text_decoration' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'family' => null,
        'weight' => null,
        'color' => null,
        'background' => null,
        'opacity' => null,
        'size' => null,
        'text_decoration' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'family' => false,
        'weight' => true,
        'color' => false,
        'background' => false,
        'opacity' => false,
        'size' => false,
        'text_decoration' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'family' => 'family',
        'weight' => 'weight',
        'color' => 'color',
        'background' => 'background',
        'opacity' => 'opacity',
        'size' => 'size',
        'text_decoration' => 'textDecoration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'family' => 'setFamily',
        'weight' => 'setWeight',
        'color' => 'setColor',
        'background' => 'setBackground',
        'opacity' => 'setOpacity',
        'size' => 'setSize',
        'text_decoration' => 'setTextDecoration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'family' => 'getFamily',
        'weight' => 'getWeight',
        'color' => 'getColor',
        'background' => 'getBackground',
        'opacity' => 'getOpacity',
        'size' => 'getSize',
        'text_decoration' => 'getTextDecoration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TEXT_DECORATION_NONE = 'none';
    public const TEXT_DECORATION_UNDERLINE = 'underline';
    public const TEXT_DECORATION_LINE_THROUGH = 'line-through';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTextDecorationAllowableValues()
    {
        return [
            self::TEXT_DECORATION_NONE,
            self::TEXT_DECORATION_UNDERLINE,
            self::TEXT_DECORATION_LINE_THROUGH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('family', $data ?? [], null);
        $this->setIfExists('weight', $data ?? [], null);
        $this->setIfExists('color', $data ?? [], null);
        $this->setIfExists('background', $data ?? [], null);
        $this->setIfExists('opacity', $data ?? [], 1);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('text_decoration', $data ?? [], 'none');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['color']) && !preg_match("/^#[A-Fa-f0-9]{6}$/", $this->container['color'])) {
            $invalidProperties[] = "invalid value for 'color', must be conform to the pattern /^#[A-Fa-f0-9]{6}$/.";
        }

        if (!is_null($this->container['background']) && !preg_match("/^#[A-Fa-f0-9]{6}$/", $this->container['background'])) {
            $invalidProperties[] = "invalid value for 'background', must be conform to the pattern /^#[A-Fa-f0-9]{6}$/.";
        }

        if (!is_null($this->container['opacity']) && ($this->container['opacity'] > 1)) {
            $invalidProperties[] = "invalid value for 'opacity', must be smaller than or equal to 1.";
        }

        if (!is_null($this->container['opacity']) && ($this->container['opacity'] < 0)) {
            $invalidProperties[] = "invalid value for 'opacity', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['size']) && ($this->container['size'] > 500)) {
            $invalidProperties[] = "invalid value for 'size', must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['size']) && ($this->container['size'] < 1)) {
            $invalidProperties[] = "invalid value for 'size', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getTextDecorationAllowableValues();
        if (!is_null($this->container['text_decoration']) && !in_array($this->container['text_decoration'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'text_decoration', must be one of '%s'",
                $this->container['text_decoration'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets family
     *
     * @return string|null
     */
    public function getFamily()
    {
        return $this->container['family'];
    }

    /**
     * Sets family
     *
     * @param string|null $family The font family for the active word. Inherits from the base font.family when not set.
     *
     * @return self
     */
    public function setFamily($family)
    {
        if (is_null($family)) {
            throw new \InvalidArgumentException('non-nullable family cannot be null');
        }
        $this->container['family'] = $family;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return mixed|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param mixed|null $weight The weight of the font for the active word. Can be a number (100-900) or a string. Inherits from the base font.weight when not set.
     *
     * @return self
     */
    public function setWeight($weight)
    {
        if (is_null($weight)) {
            array_push($this->openAPINullablesSetToNull, 'weight');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('weight', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets color
     *
     * @return string|null
     */
    public function getColor()
    {
        return $this->container['color'];
    }

    /**
     * Sets color
     *
     * @param string|null $color The active word color using hexadecimal color notation.
     *
     * @return self
     */
    public function setColor($color)
    {
        if (is_null($color)) {
            throw new \InvalidArgumentException('non-nullable color cannot be null');
        }

        if ((!preg_match("/^#[A-Fa-f0-9]{6}$/", ObjectSerializer::toString($color)))) {
            throw new \InvalidArgumentException("invalid value for \$color when calling RichCaptionActiveFont., must conform to the pattern /^#[A-Fa-f0-9]{6}$/.");
        }

        $this->container['color'] = $color;

        return $this;
    }

    /**
     * Gets background
     *
     * @return string|null
     */
    public function getBackground()
    {
        return $this->container['background'];
    }

    /**
     * Sets background
     *
     * @param string|null $background The background color behind the active word using hexadecimal color notation.
     *
     * @return self
     */
    public function setBackground($background)
    {
        if (is_null($background)) {
            throw new \InvalidArgumentException('non-nullable background cannot be null');
        }

        if ((!preg_match("/^#[A-Fa-f0-9]{6}$/", ObjectSerializer::toString($background)))) {
            throw new \InvalidArgumentException("invalid value for \$background when calling RichCaptionActiveFont., must conform to the pattern /^#[A-Fa-f0-9]{6}$/.");
        }

        $this->container['background'] = $background;

        return $this;
    }

    /**
     * Gets opacity
     *
     * @return float|null
     */
    public function getOpacity()
    {
        return $this->container['opacity'];
    }

    /**
     * Sets opacity
     *
     * @param float|null $opacity The opacity of the active word where 1 is opaque and 0 is transparent.
     *
     * @return self
     */
    public function setOpacity($opacity)
    {
        if (is_null($opacity)) {
            throw new \InvalidArgumentException('non-nullable opacity cannot be null');
        }

        if (($opacity > 1)) {
            throw new \InvalidArgumentException('invalid value for $opacity when calling RichCaptionActiveFont., must be smaller than or equal to 1.');
        }
        if (($opacity < 0)) {
            throw new \InvalidArgumentException('invalid value for $opacity when calling RichCaptionActiveFont., must be bigger than or equal to 0.');
        }

        $this->container['opacity'] = $opacity;

        return $this;
    }

    /**
     * Gets size
     *
     * @return float|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param float|null $size The font size of the active word in pixels.
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }

        if (($size > 500)) {
            throw new \InvalidArgumentException('invalid value for $size when calling RichCaptionActiveFont., must be smaller than or equal to 500.');
        }
        if (($size < 1)) {
            throw new \InvalidArgumentException('invalid value for $size when calling RichCaptionActiveFont., must be bigger than or equal to 1.');
        }

        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets text_decoration
     *
     * @return string|null
     */
    public function getTextDecoration()
    {
        return $this->container['text_decoration'];
    }

    /**
     * Sets text_decoration
     *
     * @param string|null $text_decoration Text decoration to apply to the active word.
     *
     * @return self
     */
    public function setTextDecoration($text_decoration)
    {
        if (is_null($text_decoration)) {
            throw new \InvalidArgumentException('non-nullable text_decoration cannot be null');
        }
        $allowedValues = $this->getTextDecorationAllowableValues();
        if (!in_array($text_decoration, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'text_decoration', must be one of '%s'",
                    $text_decoration,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['text_decoration'] = $text_decoration;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


