<?php
/**
 * StabilityAiGeneratedAssetOptions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Shotstack\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shotstack
 *
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Shotstack\Client\Model;

use \ArrayAccess;
use \Shotstack\Client\ObjectSerializer;

/**
 * StabilityAiGeneratedAssetOptions Class Doc Comment
 *
 * @category Class
 * @description Generate assets using Stability AI provider AI services.  The following AI generation services are available: &lt;ul&gt;   &lt;li&gt;&lt;a href&#x3D;\&quot;#tocs_stabilityaitexttoimageoptions\&quot;&gt;StabilityAiTextToImageOptions&lt;/a&gt;&lt;/li&gt; &lt;/ul&gt;
 * @package  Shotstack\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StabilityAiGeneratedAssetOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StabilityAiGeneratedAssetOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'prompt' => 'string',
        'engine' => 'string',
        'width' => 'int',
        'height' => 'int',
        'steps' => 'int',
        'seed' => 'int',
        'cfg_scale' => 'float',
        'style_preset' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'prompt' => null,
        'engine' => null,
        'width' => null,
        'height' => null,
        'steps' => null,
        'seed' => null,
        'cfg_scale' => null,
        'style_preset' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'prompt' => false,
        'engine' => false,
        'width' => false,
        'height' => false,
        'steps' => false,
        'seed' => false,
        'cfg_scale' => false,
        'style_preset' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'prompt' => 'prompt',
        'engine' => 'engine',
        'width' => 'width',
        'height' => 'height',
        'steps' => 'steps',
        'seed' => 'seed',
        'cfg_scale' => 'cfgScale',
        'style_preset' => 'stylePreset'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'prompt' => 'setPrompt',
        'engine' => 'setEngine',
        'width' => 'setWidth',
        'height' => 'setHeight',
        'steps' => 'setSteps',
        'seed' => 'setSeed',
        'cfg_scale' => 'setCfgScale',
        'style_preset' => 'setStylePreset'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'prompt' => 'getPrompt',
        'engine' => 'getEngine',
        'width' => 'getWidth',
        'height' => 'getHeight',
        'steps' => 'getSteps',
        'seed' => 'getSeed',
        'cfg_scale' => 'getCfgScale',
        'style_preset' => 'getStylePreset'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_TEXT_TO_IMAGE = 'text-to-image';
    public const ENGINE_XL_1024_V0_9 = 'stable-diffusion-xl-1024-v0-9';
    public const ENGINE_XL_1024_V1_0 = 'stable-diffusion-xl-1024-v1-0';
    public const ENGINE_V1_6 = 'stable-diffusion-v1-6';
    public const ENGINE__512_V2_1 = 'stable-diffusion-512-v2-1';
    public const ENGINE_XL_BETA_V2_2_2 = 'stable-diffusion-xl-beta-v2-2-2';
    public const STYLE_PRESET__3D_MODEL = '3d-model';
    public const STYLE_PRESET_ANALOG_FILM = 'analog-film';
    public const STYLE_PRESET_ANIME = 'anime';
    public const STYLE_PRESET_CINEMATIC = 'cinematic';
    public const STYLE_PRESET_COMIC_BOOK = 'comic-book';
    public const STYLE_PRESET_DIGITAL_ART = 'digital-art';
    public const STYLE_PRESET_ENHANCE = 'enhance';
    public const STYLE_PRESET_FANTASY_ART = 'fantasy-art';
    public const STYLE_PRESET_ISOMETRIC = 'isometric';
    public const STYLE_PRESET_LINE_ART = 'line-art';
    public const STYLE_PRESET_LOW_POLY = 'low-poly';
    public const STYLE_PRESET_MODELING_COMPOUND = 'modeling-compound';
    public const STYLE_PRESET_NEON_PUNK = 'neon-punk';
    public const STYLE_PRESET_ORIGAMI = 'origami';
    public const STYLE_PRESET_PHOTOGRAPHIC = 'photographic';
    public const STYLE_PRESET_PIXEL_ART = 'pixel-art';
    public const STYLE_PRESET_TILE_TEXTURE = 'tile-texture';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_TEXT_TO_IMAGE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEngineAllowableValues()
    {
        return [
            self::ENGINE_XL_1024_V0_9,
            self::ENGINE_XL_1024_V1_0,
            self::ENGINE_V1_6,
            self::ENGINE__512_V2_1,
            self::ENGINE_XL_BETA_V2_2_2,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStylePresetAllowableValues()
    {
        return [
            self::STYLE_PRESET__3D_MODEL,
            self::STYLE_PRESET_ANALOG_FILM,
            self::STYLE_PRESET_ANIME,
            self::STYLE_PRESET_CINEMATIC,
            self::STYLE_PRESET_COMIC_BOOK,
            self::STYLE_PRESET_DIGITAL_ART,
            self::STYLE_PRESET_ENHANCE,
            self::STYLE_PRESET_FANTASY_ART,
            self::STYLE_PRESET_ISOMETRIC,
            self::STYLE_PRESET_LINE_ART,
            self::STYLE_PRESET_LOW_POLY,
            self::STYLE_PRESET_MODELING_COMPOUND,
            self::STYLE_PRESET_NEON_PUNK,
            self::STYLE_PRESET_ORIGAMI,
            self::STYLE_PRESET_PHOTOGRAPHIC,
            self::STYLE_PRESET_PIXEL_ART,
            self::STYLE_PRESET_TILE_TEXTURE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('type', $data ?? [], 'text-to-image');
        $this->setIfExists('prompt', $data ?? [], null);
        $this->setIfExists('engine', $data ?? [], 'stable-diffusion-xl-1024-v1-0');
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('steps', $data ?? [], 30);
        $this->setIfExists('seed', $data ?? [], 0);
        $this->setIfExists('cfg_scale', $data ?? [], 7);
        $this->setIfExists('style_preset', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['prompt'] === null) {
            $invalidProperties[] = "'prompt' can't be null";
        }
        $allowedValues = $this->getEngineAllowableValues();
        if (!is_null($this->container['engine']) && !in_array($this->container['engine'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'engine', must be one of '%s'",
                $this->container['engine'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['width'] === null) {
            $invalidProperties[] = "'width' can't be null";
        }
        if ($this->container['height'] === null) {
            $invalidProperties[] = "'height' can't be null";
        }
        $allowedValues = $this->getStylePresetAllowableValues();
        if (!is_null($this->container['style_preset']) && !in_array($this->container['style_preset'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'style_preset', must be one of '%s'",
                $this->container['style_preset'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The type of asset to generate - set to `text-to-image` for text-to-image.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets prompt
     *
     * @return string
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string $prompt The text prompt to generate an image from.
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }
        $this->container['prompt'] = $prompt;

        return $this;
    }

    /**
     * Gets engine
     *
     * @return string|null
     */
    public function getEngine()
    {
        return $this->container['engine'];
    }

    /**
     * Sets engine
     *
     * @param string|null $engine The engine (model) to use for generating the image. Select from the list of available engines: <ul>   <li>`stable-diffusion-xl-1024-v0-9`</li>   <li>`stable-diffusion-xl-1024-v1-0`</li>   <li>`stable-diffusion-v1-6`</li>   <li>`stable-diffusion-512-v2-1`</li>   <li>`stable-diffusion-xl-beta-v2-2-2`</li> </ul>
     *
     * @return self
     */
    public function setEngine($engine)
    {
        if (is_null($engine)) {
            throw new \InvalidArgumentException('non-nullable engine cannot be null');
        }
        $allowedValues = $this->getEngineAllowableValues();
        if (!in_array($engine, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'engine', must be one of '%s'",
                    $engine,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['engine'] = $engine;

        return $this;
    }

    /**
     * Gets width
     *
     * @return int
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int $width The width of the image in pixels. Must be divisible by 64.
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            throw new \InvalidArgumentException('non-nullable width cannot be null');
        }
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int $height The height of the image in pixels. Must be divisible by 64.
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            throw new \InvalidArgumentException('non-nullable height cannot be null');
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets steps
     *
     * @return int|null
     */
    public function getSteps()
    {
        return $this->container['steps'];
    }

    /**
     * Sets steps
     *
     * @param int|null $steps The number of iterative diffusion steps to run. A number between 10 and 50.
     *
     * @return self
     */
    public function setSteps($steps)
    {
        if (is_null($steps)) {
            throw new \InvalidArgumentException('non-nullable steps cannot be null');
        }
        $this->container['steps'] = $steps;

        return $this;
    }

    /**
     * Gets seed
     *
     * @return int|null
     */
    public function getSeed()
    {
        return $this->container['seed'];
    }

    /**
     * Sets seed
     *
     * @param int|null $seed Using the same seed can help you create images that look similar. Set to 0 for a random seed. A number between 0 and 4294967295.
     *
     * @return self
     */
    public function setSeed($seed)
    {
        if (is_null($seed)) {
            throw new \InvalidArgumentException('non-nullable seed cannot be null');
        }
        $this->container['seed'] = $seed;

        return $this;
    }

    /**
     * Gets cfg_scale
     *
     * @return float|null
     */
    public function getCfgScale()
    {
        return $this->container['cfg_scale'];
    }

    /**
     * Sets cfg_scale
     *
     * @param float|null $cfg_scale Determines how closely the generated image will match the prompt. Lower numbers allow for more creative freedom. A number between 0 and 35.
     *
     * @return self
     */
    public function setCfgScale($cfg_scale)
    {
        if (is_null($cfg_scale)) {
            throw new \InvalidArgumentException('non-nullable cfg_scale cannot be null');
        }
        $this->container['cfg_scale'] = $cfg_scale;

        return $this;
    }

    /**
     * Gets style_preset
     *
     * @return string|null
     */
    public function getStylePreset()
    {
        return $this->container['style_preset'];
    }

    /**
     * Sets style_preset
     *
     * @param string|null $style_preset Apply a preset to generate an image in a particular style. Select from the list of available presets: <ul>   <li>`3d-model`</li>   <li>`analog-film`</li>   <li>`anime`</li>   <li>`cinematic`</li>   <li>`comic-book`</li>   <li>`digital-art`</li>   <li>`enhance`</li>   <li>`fantasy-art`</li>   <li>`isometric`</li>   <li>`line-art`</li>   <li>`low-poly`</li>   <li>`modeling-compound`</li>   <li>`neon-punk`</li>   <li>`origami`</li>   <li>`photographic`</li>   <li>`pixel-art`</li>   <li>`tile-texture`</li> </ul>
     *
     * @return self
     */
    public function setStylePreset($style_preset)
    {
        if (is_null($style_preset)) {
            throw new \InvalidArgumentException('non-nullable style_preset cannot be null');
        }
        $allowedValues = $this->getStylePresetAllowableValues();
        if (!in_array($style_preset, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'style_preset', must be one of '%s'",
                    $style_preset,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['style_preset'] = $style_preset;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


