<?php
/**
 * Tween
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shotstack
 *
 * Official PHP SDK for the Shotstack Cloud Video Editing API
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ShotstackClient\Model;

use \ArrayAccess;
use \ShotstackClient\ObjectSerializer;

/**
 * Tween Class Doc Comment
 *
 * @category Class
 * @description Use a Tween to [animate properties over time](/docs/guide/architecting-an-application/animations/). The following properties are currently supported and can be animated:   &lt;ul&gt;     &lt;li&gt;Opacity - animate the transparency of a clip.&lt;/li&gt;     &lt;li&gt;Offset - animate the x and y position of a clip.&lt;/li&gt;     &lt;li&gt;Rotation - animate the rotation of a clip.&lt;/li&gt;     &lt;li&gt;Skew - animate the horizontal and vertical shearing effect.&lt;/li&gt;     &lt;li&gt;Volume - animate the audio volume of a clip.&lt;/li&gt;   &lt;/ul&gt;
 * @package  ShotstackClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Tween implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Tween';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'from' => 'mixed',
        'to' => 'mixed',
        'start' => 'float',
        'length' => 'float',
        'interpolation' => 'string',
        'easing' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'from' => null,
        'to' => null,
        'start' => null,
        'length' => null,
        'interpolation' => null,
        'easing' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'from' => true,
        'to' => true,
        'start' => false,
        'length' => false,
        'interpolation' => false,
        'easing' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'from' => 'from',
        'to' => 'to',
        'start' => 'start',
        'length' => 'length',
        'interpolation' => 'interpolation',
        'easing' => 'easing'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'from' => 'setFrom',
        'to' => 'setTo',
        'start' => 'setStart',
        'length' => 'setLength',
        'interpolation' => 'setInterpolation',
        'easing' => 'setEasing'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'from' => 'getFrom',
        'to' => 'getTo',
        'start' => 'getStart',
        'length' => 'getLength',
        'interpolation' => 'getInterpolation',
        'easing' => 'getEasing'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INTERPOLATION_LINEAR = 'linear';
    public const INTERPOLATION_BEZIER = 'bezier';
    public const INTERPOLATION_CONSTANT = 'constant';
    public const EASING_EASE = 'ease';
    public const EASING_EASE_IN = 'easeIn';
    public const EASING_EASE_OUT = 'easeOut';
    public const EASING_EASE_IN_OUT = 'easeInOut';
    public const EASING_EASE_IN_QUAD = 'easeInQuad';
    public const EASING_EASE_IN_CUBIC = 'easeInCubic';
    public const EASING_EASE_IN_QUART = 'easeInQuart';
    public const EASING_EASE_IN_QUINT = 'easeInQuint';
    public const EASING_EASE_IN_SINE = 'easeInSine';
    public const EASING_EASE_IN_EXPO = 'easeInExpo';
    public const EASING_EASE_IN_CIRC = 'easeInCirc';
    public const EASING_EASE_IN_BACK = 'easeInBack';
    public const EASING_EASE_OUT_QUAD = 'easeOutQuad';
    public const EASING_EASE_OUT_CUBIC = 'easeOutCubic';
    public const EASING_EASE_OUT_QUART = 'easeOutQuart';
    public const EASING_EASE_OUT_QUINT = 'easeOutQuint';
    public const EASING_EASE_OUT_SINE = 'easeOutSine';
    public const EASING_EASE_OUT_EXPO = 'easeOutExpo';
    public const EASING_EASE_OUT_CIRC = 'easeOutCirc';
    public const EASING_EASE_OUT_BACK = 'easeOutBack';
    public const EASING_EASE_IN_OUT_QUAD = 'easeInOutQuad';
    public const EASING_EASE_IN_OUT_CUBIC = 'easeInOutCubic';
    public const EASING_EASE_IN_OUT_QUART = 'easeInOutQuart';
    public const EASING_EASE_IN_OUT_QUINT = 'easeInOutQuint';
    public const EASING_EASE_IN_OUT_SINE = 'easeInOutSine';
    public const EASING_EASE_IN_OUT_EXPO = 'easeInOutExpo';
    public const EASING_EASE_IN_OUT_CIRC = 'easeInOutCirc';
    public const EASING_EASE_IN_OUT_BACK = 'easeInOutBack';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInterpolationAllowableValues()
    {
        return [
            self::INTERPOLATION_LINEAR,
            self::INTERPOLATION_BEZIER,
            self::INTERPOLATION_CONSTANT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEasingAllowableValues()
    {
        return [
            self::EASING_EASE,
            self::EASING_EASE_IN,
            self::EASING_EASE_OUT,
            self::EASING_EASE_IN_OUT,
            self::EASING_EASE_IN_QUAD,
            self::EASING_EASE_IN_CUBIC,
            self::EASING_EASE_IN_QUART,
            self::EASING_EASE_IN_QUINT,
            self::EASING_EASE_IN_SINE,
            self::EASING_EASE_IN_EXPO,
            self::EASING_EASE_IN_CIRC,
            self::EASING_EASE_IN_BACK,
            self::EASING_EASE_OUT_QUAD,
            self::EASING_EASE_OUT_CUBIC,
            self::EASING_EASE_OUT_QUART,
            self::EASING_EASE_OUT_QUINT,
            self::EASING_EASE_OUT_SINE,
            self::EASING_EASE_OUT_EXPO,
            self::EASING_EASE_OUT_CIRC,
            self::EASING_EASE_OUT_BACK,
            self::EASING_EASE_IN_OUT_QUAD,
            self::EASING_EASE_IN_OUT_CUBIC,
            self::EASING_EASE_IN_OUT_QUART,
            self::EASING_EASE_IN_OUT_QUINT,
            self::EASING_EASE_IN_OUT_SINE,
            self::EASING_EASE_IN_OUT_EXPO,
            self::EASING_EASE_IN_OUT_CIRC,
            self::EASING_EASE_IN_OUT_BACK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('start', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('interpolation', $data ?? [], null);
        $this->setIfExists('easing', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getInterpolationAllowableValues();
        if (!is_null($this->container['interpolation']) && !in_array($this->container['interpolation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'interpolation', must be one of '%s'",
                $this->container['interpolation'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getEasingAllowableValues();
        if (!is_null($this->container['easing']) && !in_array($this->container['easing'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'easing', must be one of '%s'",
                $this->container['easing'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets from
     *
     * @return mixed|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param mixed|null $from The initial property value at the start of the animation.
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            array_push($this->openAPINullablesSetToNull, 'from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets to
     *
     * @return mixed|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param mixed|null $to The final property value at the end of the animation.
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            array_push($this->openAPINullablesSetToNull, 'to');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('to', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets start
     *
     * @return float|null
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param float|null $start The time in seconds when the animation starts, relative to the clip, not the timeline.
     *
     * @return self
     */
    public function setStart($start)
    {
        if (is_null($start)) {
            throw new \InvalidArgumentException('non-nullable start cannot be null');
        }
        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets length
     *
     * @return float|null
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param float|null $length The duration of the animation in seconds.
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets interpolation
     *
     * @return string|null
     */
    public function getInterpolation()
    {
        return $this->container['interpolation'];
    }

    /**
     * Sets interpolation
     *
     * @param string|null $interpolation The interpolation method to use for the animation. Available options are: <ul>   <li>`linear` - a linear interpolation between the start and end values.</li>   <li>`bezier` - a bezier curve interpolation between the start and end values.</li>   <li>`constant` - an interpolation where the property instantly jumps from the start to the end value, without any gradual transition.</li> </ul>
     *
     * @return self
     */
    public function setInterpolation($interpolation)
    {
        if (is_null($interpolation)) {
            throw new \InvalidArgumentException('non-nullable interpolation cannot be null');
        }
        $allowedValues = $this->getInterpolationAllowableValues();
        if (!in_array($interpolation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'interpolation', must be one of '%s'",
                    $interpolation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['interpolation'] = $interpolation;

        return $this;
    }

    /**
     * Gets easing
     *
     * @return string|null
     */
    public function getEasing()
    {
        return $this->container['easing'];
    }

    /**
     * Sets easing
     *
     * @param string|null $easing The easing function to use for the animation. Easing controls the rate of change of the animated value, allowing for more natural motion by speeding up or slowing down the animation at different points. Only applicable if interpolation is set to `bezier`.
     *
     * @return self
     */
    public function setEasing($easing)
    {
        if (is_null($easing)) {
            throw new \InvalidArgumentException('non-nullable easing cannot be null');
        }
        $allowedValues = $this->getEasingAllowableValues();
        if (!in_array($easing, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'easing', must be one of '%s'",
                    $easing,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['easing'] = $easing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


